server:
  port: 80
spring:
  datasource:
    username: root
    password: www1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/batch?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    schema: classpath*:/org/springframework/batch/core/schema-mysql.sql
  thymeleaf:
    prefix: classpath:/templates/
  application:
    name: AdminClient
  boot:
    admin:
      client:
        url: "http://localhost:8888"
        username: kingcall
        password: www1234
  batch:
    initialize-schema: always
#    job:
#      names: nestedChild1Job
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点 shutdown 默认是关闭的
    shutdown:
      enabled: true
